# Generated by Django 4.0.4 on 2022-05-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
