# Generated by Django 4.0.4 on 2022-05-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('NON', 'None'), ('TLS', 'Tools'), ('LAN', 'Languages'), ('PRJ', 'Projects')], default='NON', max_length=3),
        ),
    ]
