# Generated by Django 4.0.4 on 2022-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_page_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
