# Generated by Django 4.0.4 on 2022-05-08 17:10

from django.db import migrations, models

def add_default_category(apps, schema_editor):
    Category: models.Model = apps.get_model('wiki', 'Category')
    Category.objects.create(name="NON", label="None")

def revert_add_default_category(apps, schema_editor):
    Category: models.Model = apps.get_model('wiki', 'Category')
    Category.objects.filter(name="NON", label="None").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_category'),
    ]

    operations = [
        migrations.RunPython(add_default_category, revert_add_default_category)
    ]
