# Generated by Django 4.0.4 on 2022-05-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20220508_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='_category',
            field=models.ForeignKey(default='NON', on_delete=django.db.models.deletion.SET_DEFAULT, to='wiki.category'),
        ),
    ]
