# Generated by Django 4.0.4 on 2022-05-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_page__category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='_category',
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(default='NON', on_delete=django.db.models.deletion.SET_DEFAULT, to='wiki.category'),
        ),
    ]
