# Generated by Django 4.0.4 on 2022-05-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_remove_page__category_alter_page_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticValues',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
