# Generated by Django 4.0.4 on 2022-05-08 17:33

from django.db import migrations, models


def set_app_title(apps, schema_editor):
    StaticValue: models.Model = apps.get_model('wiki', 'StaticValues')
    StaticValue.objects.create(key='title', value='Notes Wiki')

def revert_set_app_title(apps, schema_editor):
    StaticValue: models.Model = apps.get_model('wiki', 'StaticValues')
    StaticValue.objects.filter(key='title', value='Notes Wiki').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_staticvalues'),
    ]

    operations = [
        migrations.RunPython(set_app_title, revert_set_app_title)
    ]
