# Generated by Django 4.0.4 on 2022-05-13 14:15

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_page_author_page_date_modified_page_date_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageColors',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
            ],
        ),
    ]
