# Generated by Django 4.0.4 on 2022-05-13 14:17

from django.db import migrations
from wiki import models

def set_colors(apps, schema_editor):
    PageColor: models.Model = apps.get_model('wiki', 'PageColors')
    PageColor.objects.create(name='bodytext', color='#F5F5F5')
    PageColor.objects.create(name='footertext', color='#D3D3D3')
    PageColor.objects.create(name='background', color='#696969')
    PageColor.objects.create(name='ribbon', color='#000000')
    PageColor.objects.create(name='brighthighlight', color='#00FF00')
    PageColor.objects.create(name='dimhighlight', color='#008800')
    PageColor.objects.create(name='shadow', color='#FFFFFF')


def revert_set_colors(apps, schema_editor):
    PageColor: models.Model = apps.get_model('wiki', 'PageColors')
    PageColor.objects.filter(name='bodytext').delete()
    PageColor.objects.filter(name='footertext').delete()
    PageColor.objects.filter(name='background').delete()
    PageColor.objects.filter(name='ribbon').delete()
    PageColor.objects.filter(name='brighthighlight').delete()
    PageColor.objects.filter(name='dimhighlight').delete()
    PageColor.objects.filter(name='shadow').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_pagecolors'),
    ]

    operations = [
        migrations.RunPython(set_colors, revert_set_colors)
    ]
