# Generated by Django 4.0.4 on 2022-05-13 22:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_remove_page_author_remove_page_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
