# Generated by Django 4.0.4 on 2022-05-15 10:42

from django.db import migrations
from siteStyle import models


def set_sitetitle(apps, schema_editor):
    siteString: models.Model = apps.get_model('siteStyle', 'SiteString')
    siteString.objects.create(key='title', value='Notes Wiki')

def revert_settitle(apps, schema_editor):
    siteString: models.Model = apps.get_model('siteStyle', 'SiteString')
    siteString.objects.filter(key='title', value='Notes Wiki').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('siteStyle', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_sitetitle, revert_settitle)
    ]
