# Generated by Django 4.0.4 on 2022-05-15 10:46

from django.db import migrations
from siteStyle import models

def set_colors(apps, schema_editor):
    siteColor: models.Model = apps.get_model('siteStyle', 'SiteColor')
    siteColor.objects.create(name='bodytext', color='#F5F5F5')
    siteColor.objects.create(name='footertext', color='#D3D3D3')
    siteColor.objects.create(name='background', color='#696969')
    siteColor.objects.create(name='ribbon', color='#000000')
    siteColor.objects.create(name='brighthighlight', color='#00FF00')
    siteColor.objects.create(name='dimhighlight', color='#008800')
    siteColor.objects.create(name='shadow', color='#FFFFFF')


def revert_set_colors(apps, schema_editor):
    siteColor: models.Model = apps.get_model('siteStyle', 'SiteColor')
    siteColor.objects.filter(name='bodytext').delete()
    siteColor.objects.filter(name='footertext').delete()
    siteColor.objects.filter(name='background').delete()
    siteColor.objects.filter(name='ribbon').delete()
    siteColor.objects.filter(name='brighthighlight').delete()
    siteColor.objects.filter(name='dimhighlight').delete()
    siteColor.objects.filter(name='shadow').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('siteStyle', '0002_addsitetitle'),
    ]

    operations = [
        migrations.RunPython(set_colors, revert_set_colors)
    ]
