# Generated by Django 4.0.4 on 2022-05-15 11:03

from django.db import migrations
from siteStyle import models

def set_pagenotfoundcontent(apps, schema_editor):
    siteRTF: models.Model = apps.get_model('siteStyle', 'SiteRichText')
    siteRTF.objects.create(name='PageNotFoundContent', value='The requested page does not exist!')

def revert_set_pagenotfoundcontent(apps, schema_editor):
    siteRTF: models.Model = apps.get_model('siteStyle', 'SiteRichText')
    siteRTF.objects.filter(name='PageNotFoundContent').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('siteStyle', '0003_addsitecolors'),
    ]

    operations = [
        migrations.RunPython(set_pagenotfoundcontent, revert_set_pagenotfoundcontent)
    ]
