# Generated by Django 4.0.4 on 2022-05-18 13:51

from django.db import migrations
from siteStyle import models

def set_homepagecontent(apps, schema_editor):
    siteRTF: models.Model = apps.get_model('siteStyle', 'SiteRichText')
    siteRTF.objects.create(name='HomePageContent', value='Add some home page content!')

def revert_set_homepagecontent(apps, schema_editor):
    siteRTF: models.Model = apps.get_model('siteStyle', 'SiteRichText')
    siteRTF.objects.filter(name='HomePageContent').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('siteStyle', '0004_addpagenotfoundcontent'),
    ]

    operations = [
        migrations.RunPython(set_homepagecontent, revert_set_homepagecontent)
    ]
